### ISSUE TITLE
Documentation: more prominent placing of placeholder functionality

### ISSUE THREAD

**Issue by JasperHorn** [flyway/flywaydb.org#102]
I was looking for a way to introduce parameters to my sql script, but I only found references to the command-line. It wasn't until I found a stackoverflow answer mentioning a (dead link containing the word) placeholders that I realized that they were named placeholders. This was while I was looking for *exactly that functionality*.

Placeholders are a powerful tool. However, in the documentation they only get a single paragraph on a different page. I was unable to find them until I found out what they were called, and I suspect people not looking for exactly this will have an even harder time finding out about them. I think it would be good to give placeholders their own page in the documentation. That would mean that they can be found in the navigation on the left side of the page, and it's not as easy to skip over the single paragraph. Expanding that single paragraph would also be good, but giving them their own page is more pressing in my opinion.

**Comment by juliahayward** [comment]
(Just noting, the single paragraph is at https://flywaydb.org/documentation/migrations)

**Comment by MikielAgutu** [comment]
There is now a page dedicated to placeholders: https://flywaydb.org/documentation/placeholders.
