### ISSUE TITLE
Support for other databases

### ISSUE THREAD

**Issue by martinrvisser** [flyway/flywaydb.org#105]
As per 5.0 release notes:
"Important note for EnterpriseDB, Vertica, SolidDB, Phoenix and Greenplum: Support for these databases has been kept back and will be integrated later in the Flyway 5.0 series. You can keep using Flyway 4.2.0 until then."

Which 5.0 release have these been integrated into?

**Comment by axelfontaine** [comment]
None so far. We may re-add support for them in the future, but there is no ETA.

**Comment by martinrvisser** [comment]
Thanks, I have two potential customers for these databases but will mention there is no ETA
