### ISSUE TITLE
Broken links in doc pages

### ISSUE THREAD

**Issue by rbielaws** [flyway/flywaydb.org#108]
On this page 
https://flywaydb.org/documentation/callbacks
The button at the bottom of the page [Error Handlers] doesn't work.  I strongly suspect it should point to .../erroroverrides rather than .../errorhandlers

Similarly
https://flywaydb.org/documentation/articles
points to a misnamed videos link.  Minor typo in the link breaks it.

On this page
https://flywaydb.org/documentation/database/sqlserver
The link in the following text is broken
"the first schema is not set as the default due to SQL Server limitations"
I have no guess where that page may have moved to though since I don't know what it said.  Sorry.

**Comment by axelfontaine** [comment]
Thank you very much for pointing this out and investigating. That was incredibly helpful. All have now been fixed.
