### ISSUE TITLE
Provide Versioned Docs

### ISSUE THREAD

**Issue by esauser** [flyway/flywaydb.org#110]
It would be nice to be able to view the docs for each version instead of only the most recent.

**Comment by axelfontaine** [comment]
This is not something we plan to do as we don't maintain multiple versions in parallel and always encourage users to migrate to the newest one.

**Comment by cdavid15** [comment]
I hope this can be reconsidered as it’s not always possible to upgrade to the latest version and as soon as a newer version is released the old documentation is no longer available which is problematic. 

For example, I’m currently using 5.0.7 community for one project in a Oracle 12.1 database environment. 

Upgrading to the latest version if I’m not mistaken would prevent existing scripts from executing using the community version so upgrading is not an option for me and either is upgrading the database. 5.0.7 works fine for us and newer projects would adopt later versions but we will always still have a need to refer to 5.0.7 documentation. 

This makes it very difficult to onboard new users to projects as we can refer to the current documentation but then need to caveat it by something this might not be reflective of the version we are using.

**Comment by esauser** [comment]
@cdavid15 the documentation is also in [GitHub](https://github.com/flyway/flywaydb.org/tree/gh-pages/documentation), so you technically can view it as of a given version.  That was how we worked around this issue.  Unfortunately, they don't _release_ it with each version, but you can still find it if you look through the commit history.  For example, for 5.0.7, you'd look [here](https://github.com/flyway/flywaydb.org/tree/aa2ef08566b506533dbb49d93349a5bbd2e997b6/documentation).

I think a legitimate request could be for them to at least _release_ it so that it can easily be found as of a given release.
