### ISSUE TITLE
MySQL page should mention encoding issues

### ISSUE THREAD

**Issue by gbirke** [flyway/flywaydb.org#12]
The MySQL page should mention that when using output generated by `mysqldump` using the option `--hex-blob` is strongly advised when using UTF-8 encoded data.

I tried dumping a Mediwiki database (with the db using `CHARSET=BINARY` tables ) with mysqldump and re-importing it with Flyway, rendering the Wiki non-functional due to encoding issues in the i18n cache. After using the `--hex-blob` option everything was fine.

**Comment by axelfontaine** [comment]
Could this be solved by setting Flyway's encoding property?

**Comment by gbirke** [comment]
What encoding does mysqldump use for UTF-8 encoded data where the table charset is set to BINARY? If you can figure that out, then maybe it's better.

**Comment by axelfontaine** [comment]
Well it seems this can be fixed by using the proper mysqldump argument: http://nathan.rambeck.org/blog/1-preventing-encoding-issues-mysqldump
