### ISSUE TITLE
DOC: flyway 6 breaking changes

### ISSUE THREAD

**Issue by teicher** [flyway/flywaydb.org#131]
in flyway 6 several breaking changes were introduced (mostly in flyway/flyway#2218).
For example, `sqlMigrationSuffix` is no longer accpeted, now it's plural `sqlMigrationSuffixes`.
Such breaking changes should be documented in the release notes.

**Comment by juliahayward** [comment]
Indeed; I've updated the issue with a full list and added a link from the release notes. For v7 we will have any changes listed in a similar Issue (https://github.com/flyway/flyway/issues/2545) in advance of the release.
