### ISSUE TITLE
Free Trial License Links are Broken

### ISSUE THREAD

**Issue by TheSench** [flyway/flywaydb.org#132]
Several locations link to `/licenses/flyway-trial`.  These links currently redirect to the home page.

![image](https://user-images.githubusercontent.com/9260413/67628899-c00bb200-f843-11e9-8f7e-8793b3704ea3.png)

**Comment by TheSench** [comment]
@juliahayward I see you intentionally removed the `flyway-trial` license files under [commit cad29d7e](https://github.com/flyway/flywaydb.org/commit/cad29d7e7085a4fc0efb1a33b3eeb63db3efe023).  The `Start Free Trial` popups on the download page linked to those licenses.  What should the correct course of action be?  Should trial licenses be added back?  Should those links point to the `Evaluation` section of the appropriate license?  Should those links go away altogether (doubtful)?

**Comment by juliahayward** [comment]
Thanks for spotting that - we don't have a separate trial licence document now, so I've reworded the text and added links to point to the Pro / Enterprise licences (which now have paragraphs about trials).
