### ISSUE TITLE
Flyway breaks my project

### ISSUE THREAD

**Issue by cptully** [flyway/flywaydb.org#140]
I started with a post on StackOverflow:

https://stackoverflow.com/questions/59360643/implementing-flyway-in-an-existing-project

But have gotten no real help there. As stated in that post, this is an existing project that I inherited. I am trying to integrate Flyway into this project to handle the v2 migration and future migrations.

If I understand the [Spring docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-execute-flyway-database-migrations-on-startup) and the matching [Flyway docs](https://flywaydb.org/documentation/plugins/springboot), all I have to do is add the Maven dependency listed in the Flyway docs that I linked. I have done that, and only that (I have made other previous attempts to do more complicated things, but have backed out all of those changes). So the only changes from my previously working project are:

1. Add the Maven dependency
2. Comment out this line in my applicationContext.xml:
`<!-- <prop key="hibernate.hbm2ddl.auto">update</prop> -->`
so that Hibernate will not update the database.

But with those minimal changes, my project will not run:
`Dec 18, 2019 9:18:34 AM org.springframework.context.support.ClassPathXmlApplicationContext refresh
WARNING: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myEmf' defined in class path resource [resources/applicationContext.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
Exception breakpoint: AbstractApplicationContext.java:576, org.springframework.beans.factory.BeanCreationException, Error creating bean with name 'myEmf' defined in class path resource [resources/applicationContext.xml]: Invocation of init method failed`

I am at a loss for what to do...

**Comment by MikielAgutu** [comment]
@cptully Sorry you're having problems with Flyway. Could you open an issue on the main Flyway repo https://github.com/flyway/flyway/issues?
