### ISSUE TITLE
Clarify overriding order

### ISSUE THREAD

**Issue by yankee42** [flyway/flywaydb.org#20]
Here:
https://github.com/flyway/flywaydb.org/blob/f7fb7ba9fae39d7cb9c7df7752db8bae943edce8/documentation/maven/index.html#L115

it says that the overriding order is:

> System properties > External config file > Maven properties > Plugin configuration

I believe a comment on this whether this means "System properties are overridden by external config, which is overwritten by..." or "System properties override external config, which overwrite maven properties..." would be helpful.

**Comment by axelfontaine** [comment]
Good catch. It was indeed not entirely clear if > meant greater than or if it symbolized a right arrow.

Fixed.
