### ISSUE TITLE
FlywayRunner plugin on Jenkins struggling for Snowflake migration

### ISSUE THREAD

**Issue by Av000001** [flyway/flywaydb.org#236]
When [Snowflake data warehouse](https://docs.snowflake.com/en/user-guide/jdbc-configure.html) is used for migration using  [FlywayRunner plugin](https://www.jenkins.io/doc/pipeline/steps/flyway-runner/) Jenkins pipeline, it doesn't work as expected.

Flyway is configured with respective Snowflake driver to be installed for migration as in below image.

![flyway-jenkins-config](https://user-images.githubusercontent.com/72910677/96091577-69313980-0ee7-11eb-9f55-1ee0b0d4b58b.png)

While providing warehouse name in [database URL string](https://docs.snowflake.com/en/user-guide/jdbc-configure.html#examples), it produces error as:

`'**warehouse' is not recognized as an internal or external command,
operable program or batch file.**`

It seems as it is unable to interpret warehouse parameter. _If a Snowflake user is not associated with warehouse then they won't be able to migrate anyhow!!_ Even if a script contains which warehouse to be used while migration, Flyway seek it prior to looking into migration scripts.

This causes a roadblock if you want to migrate Snowflake using Flyway on Jenkins, basically CI-CD for Snowflake.

Version configuration information:

> Jenkins version: 2.260
> Available respective FlywayRunner version: 1.9 [(FlywayRunner)](https://plugins.jenkins.io/flyway-runner/)
> Installed Flyway version by Jenkins: 6.5.7 
> Installed Snowflake driver version by Flyway : 3.11.1

**Comment by Lyeeedar** [comment]
This is the repo for the Flyway website. Please create flyway issues on the flyway repo https://github.com/flyway/flyway
