### ISSUE TITLE
flyway init step is missing in "First Steps: Command-line"

### ISSUE THREAD

**Issue by vondeetzen** [flyway/flywaydb.org#27]
Just tried "First Steps: Command-line" and I had to issues.

Before running the first "flyway migrate" flyway told me his metadata table is missing

```
ERROR: Found non-empty schema "TEST" without metadata table! Use init() or set initOnMigrate to true to init
ialize the metadata table.
ERROR: Caused by: org.flywaydb.core.api.FlywayException: Found non-empty schema "TEST" without metadata tabl
e! Use init() or set initOnMigrate to true to initialize the metadata table.
ERROR: Occured in org.flywaydb.core.Flyway$1.execute() at line 840
```

So I had to first run "flyway init".

My second issue with the tutorial was, I created a file named " V1__Create_person_table.sql" and flyway told me

```
Validated 1 migration (execution time 00:00.018s)
Current version of schema "TEST": 1
Schema "TEST" is up to date. No migration necessary.
```

So it worked by setting version to 2. Or did I miss some instructions before? Tried to follow the guide as exactly as possible.

**Comment by axelfontaine** [comment]
Thank you for your comment. The guide is correct. You must have used a different DB than H2 and pointed Flyway at a non-empty schema, which triggered the error message you saw.

Init is only for existing DBs retrofitted for Flyway. The guide is written for a fresh DB to make things easier to follow.

Please try the exact steps described with H2. They should work.

Cheers
Axel

**Comment by vondeetzen** [comment]
True. Did not use H2. With H2 it works as described. Sorry for being hastily. I was using Oracle. But Schema was empty because I wanted to set up a fresh DB.

**Comment by axelfontaine** [comment]
Hmmm... It should work with an empty schema, even on Oracle. But the schema
must be completly empty
Am 22.08.2014 14:38 schrieb "Andre von Deetzen" notifications@github.com:
