### ISSUE TITLE
flyway-sbt 4.2.0 is missing from the website

### ISSUE THREAD

**Issue by gil-walzer-zocdoc** [flyway/flywaydb.org#274]
Yesterday (Thurdsay Dec. 17), one of our SBT builds started failing because this dependency went missing:

https://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.10_0.13/4.2.0/flyway-sbt-4.2.0.jar

I can no longer see it on the website; the link now gives a 404. We can work around this for now because there are mirror repositories that still have the package, but this not a permanent solution.

Thanks.

**Comment by DoodleBobBuffPants** [comment]
The artifact is also on Maven Central: https://search.maven.org/artifact/org.flywaydb/flyway-sbt/4.2.0/pom

Does this work for you?

**Comment by gil-walzer-zocdoc** [comment]
We've added that artifact to our personal artifact store, which is working.

Why was the original artifact removed?

**Comment by DoodleBobBuffPants** [comment]
As you may have noticed, our website has undergone a redesign and the artifacts being hosted on the website were redundant since all official artifiacts are hosted on Maven Central

**Comment by gil-walzer-zocdoc** [comment]
FYI, this change broke a crucial build of ours and probably many others. There are explicit instructions to use your website in SBT builds. 

https://github.com/flyway/flyway/issues/1281

Did you give any warning before deleting the artifact?

**Comment by DoodleBobBuffPants** [comment]
I agree that this needed better communication, and thanks for raising the issue with us
