### ISSUE TITLE
Out of date supported versions for CockroachDB

### ISSUE THREAD

**Issue by rafiss** [flyway/flywaydb.org#294]
The CockroachDB docs page (https://flywaydb.org/documentation/database/cockroachdb) has out-of-date supported versions. The page currently lists v19.2 as the latest supported version.

Based on https://github.com/flyway/flyway/pull/2976 it should say that the latest supported version is v20.2. 

CockroachDB also has its own docs page discussing Flyway support. (https://www.cockroachlabs.com/docs/stable/flyway.html) Perhaps the Flyway docs could link there.

**Comment by DoodleBobBuffPants** [comment]
Thanks for letting us know, we have updated the docs

**Comment by rafiss** [comment]
@DoodleBobBuffPants  Thanks for the update! I think CockroachDB v20.1 should also be listed as supported, correct?
