### ISSUE TITLE
Community integration for Nuget and Cake Build

### ISSUE THREAD

**Issue by Roemer** [flyway/flywaydb.org#369]
As I see, my chocolatey package is already there but there are some more I maintain or co-maintain.

These are the nuget package at https://www.nuget.org/packages/Flyway.CommandLine and the Cake Build plugin at https://github.com/buthomas/Cake.Flyway

Would be great to have them added as well.

**Comment by DoodleBobBuffPants** [comment]
Thanks for letting us know

The relevant PR is here: https://github.com/flyway/flywaydb.org/pull/388
