### ISSUE TITLE
Documentation - Broken image link on `Flyway Plugin Development` page

### ISSUE THREAD

**Issue by JackPGreen** [flyway/flywaydb.org#515]
On the [Flyway Plugin Development page](https://documentation.red-gate.com/fd/code-flyway-plugin-development-224002366.html), one of the images does not load:

<img width="677" alt="image" src="https://github.com/flyway/flywaydb.org/assets/8626721/0e33fa5e-4f31-40d1-a934-a1bc6efb8cf3">

The [structure of the link looks consistent in the repository](https://github.com/flyway/flyway/blob/main/documentation/Flyway%20CLI%20and%20API/Contribute/Code/Code%20-%20Flyway%20Plugin%20Development.md) with [other documentation images](https://github.com/flyway/flyway/blob/main/documentation/Flyway%20CLI%20and%20API/Contribute/Code/Code%20-%20How%20to%20Contribute.md).

**Comment by alistair-RG** [comment]
Thanks - the image was in the wrong place but should now be fixed
