### ISSUE TITLE
Need advice to solve Flywaydb Version sequence problems in 3 branches of Git.

### ISSUE THREAD

**Issue by fatbun** [flyway/flywaydb.org#72]
hi, here's my flywaydb question:

I got 3 git branches: develop, fixbug, and master. 

The latest FlywayDB script version in branch master is 1.2.43, 
and the one in branch develop is 1.2.54.
Branch fixbug's script version is update to 1.2.55, and it is based on branch master. 

I need to merge branch fixbug to branch master, and to deploy master(version 1.2.55) to production environment first. As we know, flywayDB executes scripts in order, from low version to high version. If I do so, when I deploy branch develop(version 1.2.54) to the production evironment, the scripts will not be executed or even assert errors.

How should I do? Thanks!!

**Comment by axelfontaine** [comment]
Please ask this question on StackOverflow. This issue tracker is for contributions to the Flyway website.

**Comment by fatbun** [comment]
Would you mind answer me on StackOverflow, thanks!
http://stackoverflow.com/questions/38236802/how-to-resolve-version-number-conflicts-of-script-in-flywaydb
