### ISSUE TITLE
Additional information on flyway command line maven package capabilities

### ISSUE THREAD

**Issue by taufiqkh** [flyway/flywaydb.org#81]
The documentation for the command line package does not mention the org.flywaydb:flyway-commandline artifact available on maven, its capabilities or dependencies. Is this a deliberate omission? I can see that it might be unnecessary information for users just interested in straight command line functionality, but I'm interested in bundling both it and flyway-core with our software and it would be good to know whether I'm taking advantage of an undocumented package that may or may not exist in the future, or a supported package that can expect to receive updates. I'd be happy to submit a PR but I don't know what is intentional, what is not, and what is an implementation detail.

More specifically, the information I'd like to see:
- Mention of the org.flywaydb:flyway-commandline maven artifact, with a `<dependency>` snippet similar to that for flyway-core
- Whether its database driver dependencies are compile or runtime

My use case is that I support an application (a game) for which users each have their own local database. Our application performs migrations automatically with flyway-core, but we want to support users in installing mods, as well as providing scripts with which they can create or update their databases themselves. For this we'd like to bundle the additional command line functionality in our maven builds, without rewriting it ourselves and without needing to include all the other drivers that we don't support.

**Comment by axelfontaine** [comment]
Thanks for detailing your use case. The zip artifacts are also linked from Maven Central and you can simply unpack those with the Maven dependency plugin if you need to include them.

This is a very niche requirement and adding a section to docs about this would probably confuse more people than it helps.
