### ISSUE TITLE
Get Started with the Command-line tool -> configuration is too simple.

### ISSUE THREAD

**Issue by xuyuji9000** [flyway/flywaydb.org#85]

**Comment by axelfontaine** [comment]
What exactly do you mean?

**Comment by xuyuji9000** [comment]
Thanks for your response. My problem is solved.

But it would be good on this page, https://flywaydb.org/getstarted/firststeps/commandline, the configuration guidance can be improved a bit, I spent more than reasonable time on this one to figure it out. 
IMHO, this would be easier for people to get started.
